'use strict';
const E=TrigEngine;
let settings=E.clone(E.defaults);
try{const old=JSON.parse(localStorage.getItem('trig-graph-v1-settings'));if(old&&Array.isArray(old.levels)&&old.levels.length===6){const migrated=E.normalizeSettings(old);if(E.validate(migrated).length===0)settings=migrated;}}catch{}
const $=s=>document.querySelector(s),lanes=[],names=['左區','中區','右區'],transformNames={horizontalShift:'左右平移',horizontalScale:'左右伸縮',verticalScale:'上下伸縮',verticalShift:'上下平移'};
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3300);}
function applyTheme(){document.body.dataset.theme=settings.theme;}
applyTheme();
for(let i=0;i<3;i++){
const el=document.createElement('section');el.className='lane';el.setAttribute('aria-label',names[i]+'遊戲區');el.innerHTML=`<div class="lane-head"><span class="lane-name">${names[i]} · 挑戰區</span><span class="seat-label">等待下一位</span></div><div class="progress"></div><div class="question"><div class="question-meta"><span class="stars">★</span><span class="counter"></span><span class="countdown" role="timer">— 秒</span></div><div class="formula">f(x) = sin(x)</div></div><div class="plot-wrap"><canvas aria-label="${names[i]}函數繪圖區"></canvas><span class="plot-hint">範圍 −2π ～ 2π</span></div><div class="result-strip"><span class="score"></span><span class="result-detail"></span></div><div class="ink-state" role="status">用細筆畫出函數圖</div><div class="toolbar"><button class="quiet tool active" data-tool="pen">細筆</button><button class="quiet tool" data-tool="eraser">橡皮擦</button><button class="quiet" data-action="undo">復原</button></div><button class="submit">確定送出</button><div class="overlay"></div>`;
$('#lanes').appendChild(el);const l={i,el,canvas:el.querySelector('canvas'),ctx:el.querySelector('canvas').getContext('2d'),status:'idle',strokes:[],undo:[],tool:'pen',pointer:null,blocked:false,blockReason:'',frame:0};lanes.push(l);
el.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(l,b.dataset.tool));el.querySelector('[data-action=undo]').onclick=()=>{if(l.status!=='drawing'||l.pointer!==null)return;if(l.undo.length){l.strokes=l.undo.pop();updateInk(l);draw(l);}};
el.querySelector('.submit').onclick=()=>submit(l);
const c=l.canvas;c.addEventListener('pointerdown',e=>pointerDown(l,e));c.addEventListener('pointermove',e=>pointerMove(l,e));['pointerup','pointercancel','lostpointercapture'].forEach(t=>c.addEventListener(t,e=>pointerEnd(l,e)));
new ResizeObserver(()=>resize(l)).observe(el.querySelector('.plot-wrap'));welcome(l);
}
function seatOptions(selected=''){return '<option value="">不選座號</option>'+Array.from({length:settings.seatMax-settings.seatMin+1},(_,i)=>{let n=settings.seatMin+i;return `<option value="${n}" ${String(n)===String(selected)?'selected':''}>${n} 號</option>`;}).join('');}
function welcome(l){l.status='idle';l.pointer=null;l.deadline=null;l.feedbackDeadline=null;l.el.querySelector('.countdown').textContent='— 秒';l.el.querySelector('.countdown').classList.remove('urgent');l.el.classList.remove('result-mode');l.el.querySelector('.seat-label').textContent='等待下一位';l.el.querySelector('.result-strip').classList.remove('visible');let o=l.el.querySelector('.overlay');o.hidden=false;o.style.display='flex';o.innerHTML=`<div class="welcome-icon">∿</div><span class="mini-stars">★★★★★★</span><h2>準備畫出你的曲線</h2><p>從基礎圖形一路挑戰正餘弦疊合<br>完成後換下一位同學上場</p><label>${names[l.i]}座號（可不選）<select aria-label="${names[l.i]}座號">${seatOptions()}</select></label><button class="primary">開始挑戰</button><p class="welcome-detail">共 ${E.buildPlan(settings).length} 題 · 每題限時繪圖</p>`;o.querySelector('button').onclick=()=>start(l,o.querySelector('select').value);draw(l);}
function start(l,seat){l.config=E.clone(settings);l.plan=E.buildPlan(l.config);l.index=0;l.seat=seat;l.scores=[];l.attempts=0;l.history=[];l.el.querySelector('.seat-label').textContent=seat?seat+' 號':'未填座號';l.el.querySelector('.overlay').style.display='none';newQuestion(l);}
function newQuestion(l){const star=l.plan[l.index],avoid=lanes.filter(o=>o!==l&&o.q).map(o=>E.signature(o.q)).concat(l.history.slice(-8));l.q=E.selectQuestion(star,l.config.levels[star-1],avoid);l.history.push(E.signature(l.q));l.status='drawing';l.strokes=[];l.undo=[];l.pointer=null;l.result=null;l.range=E.graphRange(l.q);l.deadline=performance.now()+l.config.levels[star-1].seconds*1000;l.feedbackDeadline=null;l.budget=E.inkBudget(l.q);l.blocked=false;l.blockReason='';setTool(l,'pen');l.el.classList.remove('result-mode');l.el.querySelector('.result-strip').classList.remove('visible');l.el.querySelector('.stars').textContent='★'.repeat(star);l.el.querySelector('.counter').textContent=`第 ${l.index+1} / ${l.plan.length} 題`;l.el.querySelector('.formula').innerHTML=E.formula(l.q);l.el.querySelector('.plot-hint').textContent='範圍 −2π ～ 2π';l.el.querySelector('.progress').innerHTML=Array.from({length:6},(_,i)=>`<span class="step ${l.plan.slice(0,l.index).includes(i+1)&&!l.plan.slice(l.index).includes(i+1)?'done':star===i+1?'current':''}" title="${i+1} 星"></span>`).join('');l.el.querySelector('.submit').textContent='確定送出';l.el.querySelector('.submit').disabled=false;l.el.querySelector('[data-action=undo]').disabled=false;l.el.querySelectorAll('[data-tool]').forEach(b=>b.disabled=false);updateInk(l);updateClock(l);fitFormula(l);draw(l);}
function setTool(l,tool){if(l.pointer!==null)return;l.tool=tool;l.el.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));l.canvas.style.cursor=tool==='pen'?'crosshair':'cell';}
function geometry(l){let w=l.width||300,h=l.height||350;return {left:w>500?45:36,right:w-17,top:29,bottom:h-35};}
function toPixel(l,p){let g=geometry(l);return {x:g.left+(p.x-E.XMIN)/(E.XMAX-E.XMIN)*(g.right-g.left),y:g.bottom-(p.y-(l.range?.min??-6))/((l.range?.max??6)-(l.range?.min??-6))*(g.bottom-g.top)};}
function toPoint(l,e){const rect=l.canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,g=geometry(l);if(x<g.left||x>g.right||y<g.top||y>g.bottom)return null;return {x:E.XMIN+(x-g.left)/(g.right-g.left)*(E.XMAX-E.XMIN),y:(l.range?.min??-6)+(g.bottom-y)/(g.bottom-g.top)*((l.range?.max??6)-(l.range?.min??-6))};}
function fitFormula(l){
 const node=l.el.querySelector('.formula');node.style.fontSize='';
 if(!node.clientWidth||node.scrollWidth<=node.clientWidth)return;
 let size=parseFloat(getComputedStyle(node).fontSize);
 while(node.scrollWidth>node.clientWidth&&size>14){size-=.5;node.style.fontSize=size+'px';}
}
function resize(l){fitFormula(l);const r=l.canvas.getBoundingClientRect();l.width=r.width;l.height=r.height;const dpr=Math.min(window.devicePixelRatio||1,2);l.canvas.width=Math.round(r.width*dpr);l.canvas.height=Math.round(r.height*dpr);l.ctx.setTransform(dpr,0,0,dpr,0,0);draw(l);}
function draw(l){const c=l.ctx,w=l.width||l.canvas.clientWidth,h=l.height||l.canvas.clientHeight;if(!w||!h)return;c.clearRect(0,0,w,h);const g=geometry(l),range=l.range||E.graphRange(l.q),dark=settings.theme==='dark',axis=dark?'#b9c9dd':'#536781',text=dark?'#a8b9cf':'#65778c';c.save();c.beginPath();c.rect(g.left,g.top,g.right-g.left,g.bottom-g.top);c.clip();c.lineWidth=Number(settings.gridWidth);c.strokeStyle=settings.gridColor;
for(let k=-8;k<=8;k++){let x=toPixel(l,{x:k*Math.PI/4,y:0}).x;c.beginPath();c.moveTo(x,g.top);c.lineTo(x,g.bottom);c.stroke();}for(let y=range.min;y<=range.max+1e-8;y+=range.step){let py=toPixel(l,{x:0,y}).y;c.beginPath();c.moveTo(g.left,py);c.lineTo(g.right,py);c.stroke();}
const zero=toPixel(l,{x:0,y:0});c.lineWidth=1.5;c.strokeStyle=axis;c.beginPath();c.moveTo(zero.x,g.top);c.lineTo(zero.x,g.bottom);c.moveTo(g.left,zero.y);c.lineTo(g.right,zero.y);c.stroke();
function paths(strokes,color,width,dash=[]){c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.setLineDash(dash);for(let s of strokes){if(!s.length)continue;c.beginPath();let p=toPixel(l,s[0]);c.moveTo(p.x,p.y);for(let j=1;j<s.length;j++){p=toPixel(l,s[j]);c.lineTo(p.x,p.y);}if(s.length===1){c.lineTo(p.x+.2,p.y+.2);}c.stroke();}c.setLineDash([]);}
const accent=getComputedStyle(l.el).getPropertyValue('--accent').trim();paths(l.strokes,dark?(l.i===0?'#aaa4ff':l.i===1?'#45d9c5':'#ffd080'):accent,2.2);
if(l.status==='result'&&l.q){if(l.q.type==='tan'){c.strokeStyle=dark?'#d99b76':'#d4a58a';c.lineWidth=1;c.setLineDash([3,7]);for(let k=-12;k<=12;k++){let x=l.q.h+(Math.PI/2+k*Math.PI)/l.q.b;if(x<E.XMIN||x>E.XMAX)continue;let px=toPixel(l,{x,y:0}).x;c.beginPath();c.moveTo(px,g.top);c.lineTo(px,g.bottom);c.stroke();}c.setLineDash([]);}paths(E.targetPaths(l.q),dark?'#ffab5e':'#df641c',2.4,[7,6]);for(let sample of l.result.points){if(sample.excluded)continue;let p=toPixel(l,{x:sample.x,y:sample.target});c.fillStyle=sample.value>=.8?(dark?'#75d9b3':'#2d9b70'):(dark?'#ffab5e':'#df641c');c.beginPath();c.arc(p.x,p.y,2.8,0,Math.PI*2);c.fill();}}
c.restore();c.fillStyle=text;c.font=(w>500?'15':'13')+'px "Microsoft JhengHei", sans-serif';c.textAlign='center';c.textBaseline='top';const labels=['−2π','−3π/2','−π','−π/2','0','π/2','π','3π/2','2π'];for(let i=0;i<9;i++){if(w<360&&i%2)continue;let p=toPixel(l,{x:(i-4)*Math.PI/2,y:0});c.fillText(labels[i],p.x,g.bottom+9);}c.textAlign='right';c.textBaseline='middle';const labelEvery=Math.max(1,Math.ceil(17/((g.bottom-g.top)/(range.max-range.min)*range.step)));for(let y=range.min;y<=range.max+1e-8;y+=range.step){if(y===0||Math.abs(y/(range.step*labelEvery)-Math.round(y/(range.step*labelEvery)))>1e-8)continue;let p=toPixel(l,{x:0,y});c.fillText(String(y),g.left-7,p.y);}c.textAlign='left';c.textBaseline='top';c.fillText('y',g.left-12,7);c.textAlign='right';c.fillText('x',g.right,7);
}
function saveUndo(l){l.undo.push(l.strokes.map(s=>s.map(p=>({...p}))));if(l.undo.length>12)l.undo.shift();}
function pointerDown(l,e){if(l.status==='drawing'&&performance.now()>=l.deadline){submit(l,true);return;}if(l.status!=='drawing'||l.pointer!==null||e.button>0)return;let p=toPoint(l,e);if(!p)return;e.preventDefault();if(l.tool==='pen'&&l.blocked){updateInk(l);return;}saveUndo(l);l.pointer=e.pointerId;l.last=p;l.active=null;l.pointerTool=l.tool;l.canvas.setPointerCapture(e.pointerId);if(l.tool==='pen'){l.active=[p];l.strokes.push(l.active);}else l.strokes=E.erase(l.strokes,p,22,l.range);updateInk(l);draw(l);}
function pointerMove(l,e){if(l.status==='drawing'&&performance.now()>=l.deadline){submit(l,true);return;}if(l.pointer!==e.pointerId||l.status!=='drawing')return;e.preventDefault();const events=e.getCoalescedEvents?e.getCoalescedEvents():[e];for(let event of events.length?events:[e]){let p=toPoint(l,event);if(!p){l.last=null;l.active=null;continue;}if(l.pointerTool==='pen'){if(l.blocked)break;if(!l.active){l.active=[p];l.strokes.push(l.active);l.last=p;continue;}appendInterpolated(l,p);if(E.length(l.strokes,l.range)>l.budget||E.tooManyYs(l.strokes,l.range)){updateInk(l);break;}}else{const a=l.last||p,steps=Math.max(1,Math.ceil(Math.hypot((p.x-a.x)/(4*Math.PI)*600,(p.y-a.y)/(l.range.max-l.range.min)*500)/8));for(let i=1;i<=steps;i++)l.strokes=E.erase(l.strokes,{x:a.x+(p.x-a.x)*i/steps,y:a.y+(p.y-a.y)*i/steps},22,l.range);l.last=p;}}
updateInk(l);if(!l.frame)l.frame=requestAnimationFrame(()=>{l.frame=0;draw(l);});}
function appendInterpolated(l,p){let a=l.last||p,steps=Math.max(1,Math.ceil(Math.hypot((p.x-a.x)/(4*Math.PI)*600,(p.y-a.y)/(l.range.max-l.range.min)*500)/3));for(let i=1;i<=steps;i++)l.active.push({x:a.x+(p.x-a.x)*i/steps,y:a.y+(p.y-a.y)*i/steps});l.last=p;}
function pointerEnd(l,e){if(l.pointer!==e.pointerId)return;if(e.type==='pointerup'&&l.status==='drawing')pointerMove(l,e);l.pointer=null;l.active=null;l.last=null;updateInk(l);draw(l);}
function updateInk(l){if(l.status!=='drawing')return;let long=E.length(l.strokes,l.range)>l.budget,multi=E.tooManyYs(l.strokes,l.range);l.blocked=long||multi;l.blockReason=multi?'同一 x 的筆跡過多':'筆跡長度超出用量';const el=l.el.querySelector('.ink-state');el.classList.toggle('exhausted',l.blocked);el.textContent=l.blocked?'墨水已耗盡，請用橡皮擦擦除筆跡':'用細筆畫出函數圖 · 畫錯可擦除';}
function releasePointer(l){
 const id=l.pointer;l.pointer=null;l.active=null;l.last=null;
 if(id!==null&&l.canvas.hasPointerCapture(id))l.canvas.releasePointerCapture(id);
}
function updateClock(l,now=performance.now()){
 const badge=l.el.querySelector('.countdown');
 if(l.status==='drawing'){
  const seconds=Math.max(0,Math.ceil((l.deadline-now)/1000));badge.textContent=seconds+' 秒';badge.classList.toggle('urgent',seconds<=10);
  if(now>=l.deadline)submit(l,true);
 }else if(l.status==='result'){
  const seconds=Math.max(0,Math.ceil((l.feedbackDeadline-now)/1000));badge.textContent='已評分';badge.classList.remove('urgent');
  l.el.querySelector('.submit').textContent=seconds+' 秒後'+(l.index+1>=l.plan.length?'顯示總分':'自動換題');
  if(now>=l.feedbackDeadline){l.index++;if(l.index>=l.plan.length)finish(l);else newQuestion(l);}
 }
}
function submit(l,timedOut=false){
 if(l.status!=='drawing')return;
 if(!timedOut&&l.pointer!==null){toast('請先將手或筆離開繪圖區，再送出。');return;}
 l.result=E.score(l.q,l.strokes);l.attempts++;l.status='result';l.deadline=null;l.feedbackDeadline=performance.now()+2000;
 releasePointer(l);l.scores.push({star:l.q.star,score:l.result.score,timedOut});
 l.el.classList.add('result-mode');l.el.querySelector('.result-strip').classList.add('visible');l.el.querySelector('.score').textContent=l.result.score+' 分';
 l.el.querySelector('.result-detail').innerHTML=`<strong>${timedOut?'時間到，已自動送出':'本題已評分'}</strong><br>完整度 ${l.result.coverage}% · 比對 ${l.result.visible}/40 點`;
 l.el.querySelector('.submit').disabled=true;l.el.querySelectorAll('[data-tool],[data-action=undo]').forEach(b=>b.disabled=true);
 l.el.querySelector('.plot-hint').textContent='實線：你的圖　虛線：參考答案';updateClock(l);draw(l);
}
function finish(l){
 l.status='finished';l.feedbackDeadline=null;l.deadline=null;const total=l.scores.reduce((s,v)=>s+v.score,0),maximum=l.plan.length*100;
 l.el.querySelector('.countdown').textContent='已完成';
 let o=l.el.querySelector('.overlay');o.style.display='flex';
 o.innerHTML=`<span class="mini-stars">★★★★★★</span><h2>${l.seat?l.seat+' 號 · ':''}闖關完成</h2><span class="big-score">${total}</span><span class="score-caption">總分 / ${maximum} 分</span><div class="summary-scores">${Array.from({length:6},(_,i)=>{let ss=l.scores.filter(s=>s.star===i+1);return `<div>${i+1} 星<strong>${ss.length?ss.reduce((a,s)=>a+s.score,0):'—'}</strong></div>`;}).join('')}</div><p>完成 ${l.scores.length} 題 · 平均 ${Math.round(total/l.scores.length)} 分</p><button class="primary">下一位學生</button>`;
 o.querySelector('button').onclick=()=>{l.q=null;l.strokes=[];l.range=null;welcome(l);};
}
setInterval(()=>{const now=performance.now();for(const lane of lanes)updateClock(lane,now);},100);
function openSettings(){const f=$('#settingsForm');for(let k of ['theme','gridColor','gridWidth','seatMin','seatMax'])f.elements[k].value=settings[k];renderLevels(settings);$('#settingsError').textContent='';$('#settingsDialog').showModal();}
function renderLevels(s){$('#levelSettings').innerHTML=s.levels.map((l,i)=>`<section class="level-card" data-level="${i}"><div class="level-title"><strong><span class="stars">${'★'.repeat(i+1)}</span> ${i===5?'正餘弦疊合':i===0?'基礎圖形':i+' 種圖形變化'}</strong><div class="level-options"><label class="time-label">限時<select name="seconds${i}">${Array.from({length:30},(_,j)=>{let seconds=(j+1)*10;return `<option value="${seconds}" ${l.seconds===seconds?'selected':''}>${seconds} 秒</option>`;}).join('')}</select></label><label class="count-label">題數<input type="number" name="count${i}" min="0" max="20" value="${l.count}" required></label></div></div>${i===5?`<div class="checks"><label><input type="checkbox" name="enabled5" ${l.enabled?'checked':''}>出現正餘弦疊合題目</label></div><p>題型為 a sin x + b cos x；振幅不超過 4，疊合後平移量為 π/4 的整數倍，方便配合格線畫圖。</p>`:`<div class="checks">${['sin','cos','tan'].map(t=>`<label><input type="checkbox" name="type${i}" value="${t}" ${l.types.includes(t)?'checked':''}>${t} x</label>`).join('')}</div>${i?`<div class="checks">${E.transforms.map(t=>`<label><input type="checkbox" name="trans${i}" value="${t}" ${l.transforms.includes(t)?'checked':''}>${transformNames[t]}</label>`).join('')}</div><p>每題從勾選項目取恰好 ${i} 種變化。至少勾選 ${i} 種，或將此星等題數設為 0。</p>`:'<p>沒有圖形變化，直接畫出基礎函數。</p>'}`}</section>`).join('');}
$('#settingsForm').elements.theme.onchange=e=>{const color=$('#settingsForm').elements.gridColor;if(e.target.value==='dark'&&color.value==='#dce5f0')color.value='#2a3b54';else if(e.target.value==='light'&&color.value==='#2a3b54')color.value='#dce5f0';};
$('#settingsBtn').onclick=openSettings;$('#helpBtn').onclick=()=>$('#helpDialog').showModal();document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#defaultsBtn').onclick=()=>{let f=$('#settingsForm');for(let k of ['theme','gridColor','gridWidth','seatMin','seatMax'])f.elements[k].value=E.defaults[k];renderLevels(E.defaults);$('#settingsError').textContent='';};
$('#settingsForm').onsubmit=e=>{e.preventDefault();let f=e.target,s=E.clone(settings);for(let k of ['theme','gridColor'])s[k]=f.elements[k].value;for(let k of ['gridWidth','seatMin','seatMax'])s[k]=Number(f.elements[k].value);s.levels=Array.from({length:6},(_,i)=>({count:Number(f.elements['count'+i].value),seconds:Number(f.elements['seconds'+i].value),types:[...f.querySelectorAll(`[name="type${i}"]:checked`)].map(b=>b.value),transforms:[...f.querySelectorAll(`[name="trans${i}"]:checked`)].map(b=>b.value),enabled:i<5||f.elements.enabled5.checked}));let errs=E.validate(s);if(errs.length){$('#settingsError').textContent=errs.join(' ');return;}settings=s;try{localStorage.setItem('trig-graph-v1-settings',JSON.stringify(settings));}catch{toast('設定已套用；此瀏覽器無法保存設定。');}applyTheme();for(let l of lanes){if(l.status==='idle')welcome(l);draw(l);}$('#settingsDialog').close();toast('設定已儲存，新題目設定從下一位學生開始。');};
$('#fullBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('請使用瀏覽器全螢幕鍵（F11）。');}};document.addEventListener('fullscreenchange',()=>$('#fullBtn').textContent=document.fullscreenElement?'離開全螢幕':'全螢幕');
document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('selectstart',e=>{if(!e.target.closest?.('input,select'))e.preventDefault();});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if((e.ctrlKey&&(e.key==='u'||e.key==='U'||e.key==='+'||e.key==='-'||e.key==='='))||e.key==='F7')e.preventDefault();});
// A local bridge for automated verification; all scoring and rendering use these same functions.
window.TrigGame={lanes,get settings(){return settings;},start,newQuestion,submit,draw,updateInk,geometry,toPixel,toPoint,welcome,updateClock,finish,fitFormula};
